config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
	resource :relationships, only: [:create, :destroy]
  end

  get 'relationships/follower' => 'relationships#follower', as: 'relationships_follower'
  get 'relationships/follow' => 'relationships#follow', as: 'relationships_follow'

  post 'search' => 'search#search', as: 'search'

  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about'

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :set_variables

	def create
		book = Book.find(params[:book_id])
		book_comment = current_user.book_comments.new(book_comment_params)
		book_comment.book_id = book.id
		book_comment.save
		# redirect_back(fallback_location: root_path)
	end

	def destroy
		book_comment = current_user.book_comments.find_by(id: params[:comment_id])
		book_comment.destroy
		# redirect_back(fallback_location: root_path)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end

	def set_variables
		@book = Book.find(params[:book_id])
		@book.book_comments.all
		@id_name = "#comment-link-#{@book.id}"
	end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
	<div class="comment-link" id="comment-link-<%= book.id %>">
		<li style="list-style:none;">
			<%= book_comment.comment %>
			<% if book_comment.user_id == current_user.id %>
				<%= link_to "Destroy", book_book_comments_path(book, comment_id: book_comment.id), method: :delete, remote: true, class: "btn-sm btn-danger destroy_book_comment_#{book_comment.id}" %>
			<% end %>
		</li>
	</div>
<% end %>

app/views/book_comments/create.js.erb
$("#comment_box").html("<%= escape_javascript(render('book_comments/comment', book: @book)) %>");
$("textarea").val("");

app/views/book_comments/destroy.js.erb
$("#comment_box").html("<%= escape_javascript(render('book_comments/comment', book: @book)) %>");