config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
	resource :relationships, only: [:create, :destroy]
  end

  get 'relationships/follower' => 'relationships#follower', as: 'relationships_follower'
  get 'relationships/follow' => 'relationships#follow', as: 'relationships_follow'

  post 'search' => 'search#search', as: 'search'

  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about'

end

app/models/user.rb
class User < ApplicationRecord
  include JpPrefecture
  jp_prefecture :prefecture_code

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :relationships, dependent: :destroy
  #through: :relationships 「中間テーブルはrelationships」設定
  #source: :follow　relationshipsテーブルのfollow_idを参考にして、followingsモデルにアクセス」
  #user.followings と打つだけで、user が中間テーブル relationships を取得し、その1つ1つの relationship のfollow_idから、「フォローしている User 達」を取得しています
  has_many :followings, through: :relationships, source: :follow

  #フォロワー（フォローされているuser達）をとってくるための記述
  #has_many :relaitonshipsの「逆方向」意味
  #foreign_key: 'follow_id' elaitonshipsテーブルにアクセスする時、follow_idを入口」
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  #through: :reverses_of_relationshipで「中間テーブルはreverses_of_relationship」
  #source: :userで「出口はuser_idね！それでuserテーブルから自分をフォローしているuserをとってきてね！」と設定
  has_many :followers, through: :reverse_of_relationships, source: :user


  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  #フォローしようとしている other_user が自分自身ではないかを検証しています
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  #フォローがあればアンフォロー
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  #self.followings によりフォローしている User 達を取得し、include?(other_user) によって other_user が含まれていないかを確認
  def following?(other_user)
    self.followings.include?(other_user)
  end


  #完全一致
  def self.perfect_matching(search)
      return User.all unless search
      User.where(['name LIKE ?', "#{search}"])
  end

  #前方一致
  def self.forward_match(search)
      return User.all unless search
      User.where(['name LIKE ?', "#{search}%"])
  end

  #後方一致
  def self.backward_match(search)
      return User.all unless search
      User.where(['name LIKE ?', "%#{search}"])
  end

  #部分一致
  def self.part_match(search)
      return User.all unless search
      User.where(['name LIKE ?', "%#{search}%"])
  end

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])

    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		#redirect_to user_path(@user), notice: "successfully updated user!"You have updated user successfully.
      redirect_to user_path(@user), notice: "You have updated user successfully."
  	else
      @books = @user.books
      @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  		#render "show"
      render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
    unless params[:id].to_i == current_user.id then
      redirect_to user_path(current_user)
    end
  end

  def address_params
    #params.require(:address).permit(:zipcode, :prefecture_name, :city, :street, :building)
    #params.require(:address).permit(:zipcode, :prefecture_name, :city, :street)
    params.require(:user).permit(:postcode, :prefecture_name, :address_city, :address_street)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th>
			<%= link_to relationships_follow_path(follow_id: user.id) do %>
				<%#= Relationship.where(user_id: user.id).count %>
				<%= user.followings.count %>
			<% end %>
		</th>
	</tr>

	<tr>
		<th>followers</th>
		<th>
			<%= link_to relationships_follower_path(follow_id: user.id) do %>
				<%= Relationship.where(follow_id: user.id).count %>
			<% end %>
		</th>
	</tr>

</table>

<% unless current_user == user %>
	<% if current_user.following?(user) %>
		<%= form_for(current_user.relationships.find_by(follow_id: user.id), url: user_relationships_path(current_user), html: { method: :delete }) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'フォローを外す', class: "btn btn-primary" %>
		<% end %>
	<% else %>
		<%= form_for(current_user.relationships.build, url: user_relationships_path(current_user)) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'フォローする', class: "btn btn-success" %>
		<% end %>
	<% end %>
<% else %>
	<!-- <div class="container"> -->
		<div class="row">
			<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
		</div>
	<!-- </div> -->
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<%= render 'layouts/error_messages', model: @book %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name %></td>
						<td>フォロー数：<%= user.followings.count %></td>
						<td>フォロワー数：<%= Relationship.where(follow_id: user.id).count %></td>
						<td>
							<% unless current_user == user %>
								<% if current_user.following?(user) %>
									<%#= form_for(current_user.relationships.find_by(follow_id: user.id), url: user_relationships_path(current_user), html: { method: :delete }) do |f| %>
										<%#= hidden_field_tag  %>
										<%#= f.submit 'フォローを外す' %>
									<%# end %>
									<%= link_to 'フォローを外す', user_relationships_path(current_user, follow_id: user.id), method: :delete %>
								<% else %>
									<%#= form_for(current_user.relationships.build, url: user_relationships_path(current_user)) do |f| %>
										<%#= hidden_field_tag :follow_id, user.id %>
										<%#= f.submit 'フォローする' %>
									<%# end %>
									<%= link_to 'フォローする', user_relationships_path(current_user, follow_id: user.id), method: :post %>
								<% end %>
							<% end %>
						</td>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--users一覧 -->
		</div>
	</div>
</div>

app/views/users/show.html.erb
<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<%=javascript_tag do %>
let map
let geocoder
function initMap(){
	geocoder=new google.maps.Geocoder();
  	map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
  codeAddress();
}


function codeAddress(){
  // let inputAddress = document.getElementById('address').value;
  <% address_box = current_user.prefecture_code + current_user.address_city + current_user.address_street %>
  <!-- let inputAddress = "<%#= @user.address_city.to_s.to_json + @user.address_street.to_s.to_json %>" -->
  let inputAddress = "<%= address_box %>"
  let geocoder=new google.maps.Geocoder();
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });
}
<% end %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['API_KEY']%>&callback=initMap" async defer></script>

<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
			<!--同コントローラーのviewで表示ならusersは省略可 -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td><p>コメント数：<%= book.book_comments.count %></p></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!-- <input id="address" type="textbox" value="GeekSalon">
			<input type="button" value="Encode" onclick="codeAddress()"> -->
			<% if @user.id == current_user.id %>
				<div id='map'></div>
			<% end %>
			<!--books一覧 -->
		</div>
	</div>
</div>