config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
	resource :relationships, only: [:create, :destroy]
  end

  get 'relationships/follower' => 'relationships#follower', as: 'relationships_follower'
  get 'relationships/follow' => 'relationships#follow', as: 'relationships_follow'

  post 'search' => 'search#search', as: 'search'

  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about'

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#完全一致
	def self.perfect_matching(search)
		return Book.all unless search
		Book.where(['title LIKE ?', "#{search}"])
	end

	#前方一致
	def self.forward_match(search)
		return Book.all unless search
		Book.where(['title LIKE ?', "#{search}%"])
	end

	#後方一致
	def self.backward_match(search)
		return Book.all unless search
		Book.where(['title LIKE ?', "%#{search}"])
	end

	#部分一致
	def self.part_match(search)
		return Book.all unless search
		Book.where(['title LIKE ?', "%#{search}%"])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    #redirect_to books_path, notice: "successfully delete book!"
    redirect_to books_path, notice: "You have deleted book successfully."
  end

  def show
  	@book = Book.find(params[:id])
    #@user = User.find(params[:id])
    @user = User.find(current_user.id)
    #@book_comments = @book.book_comments.all
    @book_comment = @book.book_comments.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		#redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
      redirect_to @book, notice: "You have creatad book successfully."
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		#redirect_to @book, notice: "successfully updated book!"You have updated book successfully.
      redirect_to @book, notice: "You have updated book successfully."
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end



  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<%= render 'layouts/error_messages', model: @book %>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>
		<%= render "books/newform", book: @book %>
		<%= link_to "Show", @book, class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

		</div>
		<div class="col-md-3"></div>

	</div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/error_messages', model: @book %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th></th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<!-- いいね機能 -->
						<td>
							<%= render 'favorites/like', book: book %>
	<!-- 						<% if book.favorited_by?(current_user) %>
								<%= link_to book_favorites_path(book), method: :delete do %>
							      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							      <%= book.favorites.count %>
							    <% end %>
							<% else %>
							    <%= link_to book_favorites_path(book), method: :post do %>
							      <i class="fa fa-heart-o" aria-hidden="true"></i>
							      <%= book.favorites.count %>
							    <% end %>
							<% end %> -->
						</td>
						<td>
							<p>コメント数：<%= book.book_comments.count %></p>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<!--books一覧 -->


		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<!-- いいね機能 -->
					<td>
						<%= render 'favorites/like', book: @book %>
		<!-- 				<% if @book.favorited_by?(current_user) %>
							<%= link_to book_favorites_path(@book), method: :delete do %>
						      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
						      <%= @book.favorites.count %>
						    <% end %>
						<% else %>
						    <%= link_to book_favorites_path(@book), method: :post do %>
						      <i class="fa fa-heart-o" aria-hidden="true"></i>
						      <%= @book.favorites.count %>
						    <% end %>
						<% end %> -->
					</td>
					<td>
						<p>コメント数：<%= @book.book_comments.count %></p>
					</td>
					<% if current_user.id == @book.user_id %>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<div id="comment_box">
				<%= render 'book_comments/comment', book: @book %>
			</div>

			<div>
				<div class="row">
					<%#= form_for [@book, @book_comment] do |f| %>
					<%= form_with(model: [@book, @book_comment], remote: true) do |f| %>

						<%= f.text_area :comment, class: "col-xs-11", style: "height: 100px" %>
						<%= f.submit "送信", class: "btn btn-default pull-right" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>